docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - "Quick Start": quick-start.md
    - "Tag Clouds": tag-cloud.md
site_name: laminas-tag
site_description: Laminas\Tag
repo_url: 'https://github.com/laminas/laminas-tag'
